# Generated by Django 6.0 on 2025-12-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('publish', 'publish'), ('private', 'private')], default='draft', max_length=20),
        ),
    ]
