# Generated by Django 6.0 on 2025-12-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('publish', 'Published'), ('private', 'Private')], default='draft', max_length=20),
        ),
    ]
